name: Dedicated

on: [push, pull_request]

jobs:
  linux:
    name: Linux-x86
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Create bin folder
        run: mkdir -p game/mod_hl2mp/bin
      - name: Run VPC
        run: src/createallprojects
      - name: Build
        uses: docker://registry.gitlab.steamos.cloud/steamrt/scout/sdk/i386:latest
        with:
          args: make CFG=release GITHUB_ACTIONS=1 -f mp/src/dedicated.mak
      - name: Rename server binary
        run: mv game/mod_hl2mp/bin/server.so game/mod_hl2mp/bin/server_srv.so
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Linux-x86
          path: game/mod_hl2mp/bin/server_srv.so