name: Dedicated

on: [push, pull_request]

jobs:
  linux:
    name: Linux-x86
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Create bin folder
        run: mkdir -p game/mod_hl2mp/bin
      - name: Create .ccache folder
        run: mkdir $HOME/.ccache
      - name: Run VPC
        run: src/buildallprojects
      - name: Rename server binary
        run: mv game/mod_hl2mp/bin/linux64/server.so game/mod_hl2mp/bin/linux64/server_srv.so
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Linux-x86
          path: game/mod_hl2mp/bin/linux64/server_srv.so